from pathlib import Path
full = Path('templates/core/register.html').read_text()
start3 = full.index('<section class="adventurer-step" data-step="3">')
start4 = full.index('<section class="adventurer-step" data-step="4">')
start5 = full.index('<section class="adventurer-step" data-step="5">')
nav = full.index('<div class="form-navigation"')
print('STEP3')
print(full[start3:start4])
print('STEP4')
print(full[start4:start5])
print('STEP5')
print(full[start5:nav])
