# Generated by Django 6.0 on 2026-01-25 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responsavel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Adventurer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('document', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('allergies', models.TextField()),
                ('medication', models.TextField()),
                ('observation', models.TextField()),
                ('emergency_name', models.CharField(max_length=120)),
                ('emergency_phone', models.CharField(max_length=20)),
                ('emergency_whatsapp', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='adventure_photos/%Y/%m')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adventureiros', to='core.responsible')),
            ],
        ),
    ]
