# Generated by Django 6.0 on 2026-01-25 23:45

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_adventurer_sexo_responsible_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6)),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('D', 'Pago')], default='P', max_length=1)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('adventurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='core.adventurer')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='core.responsible')),
            ],
            options={
                'unique_together': {('adventurer', 'month', 'year')},
            },
        ),
    ]
