# Generated by Django 6.0 on 2026-01-25 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_monthlyfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyfee',
            name='due_day',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
