# Generated by Django 6.0 on 2026-01-26 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_passwordrecovery'),
    ]

    operations = [
        migrations.CreateModel(
            name='PixCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('P', 'PIX pendente'), ('A', 'PIX aprovado')], default='P', max_length=1)),
                ('mp_payment_id', models.CharField(blank=True, max_length=64, null=True)),
                ('external_reference', models.CharField(max_length=128, unique=True)),
                ('qr_code', models.TextField(blank=True, null=True)),
                ('qr_code_base64', models.TextField(blank=True, null=True)),
                ('copy_text', models.TextField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pix_charges', to='core.responsible')),
            ],
            options={
                'unique_together': {('responsible', 'year', 'month')},
            },
        ),
    ]
