# Generated by Django 6.0 on 2026-01-26 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pixcharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='pixcharge',
            name='last_notification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pixcharge',
            name='last_notification_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
