# Generated by Django 6.0 on 2026-01-26 21:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pixcharge_last_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyfee',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=6),
        ),
    ]
