# Generated by Django 6.0 on 2026-01-28 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_monthlyfee_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('term_nationality', models.CharField(blank=True, max_length=80)),
                ('term_marital_status', models.CharField(blank=True, max_length=60)),
                ('term_rg_number', models.CharField(blank=True, max_length=30)),
                ('term_rg_issuer', models.CharField(blank=True, max_length=40)),
                ('term_residence', models.CharField(blank=True, max_length=255)),
                ('term_municipality', models.CharField(blank=True, max_length=120)),
                ('term_cpf', models.CharField(blank=True, max_length=20)),
                ('term_accepted', models.BooleanField(default=False)),
                ('church', models.CharField(max_length=150)),
                ('district', models.CharField(max_length=80)),
                ('street_address', models.CharField(max_length=255)),
                ('house_number', models.CharField(max_length=20)),
                ('neighborhood', models.CharField(max_length=120)),
                ('postal_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('cellphone', models.CharField(max_length=20)),
                ('home_phone', models.CharField(blank=True, max_length=20)),
                ('work_phone', models.CharField(blank=True, max_length=20)),
                ('birth_date', models.DateField()),
                ('volunteer_marital_status', models.CharField(max_length=60)),
                ('director_cpf', models.CharField(max_length=20)),
                ('director_rg', models.CharField(max_length=30)),
                ('spouse', models.CharField(blank=True, max_length=120)),
                ('child_one', models.CharField(blank=True, max_length=120)),
                ('child_two', models.CharField(blank=True, max_length=120)),
                ('health_limitation', models.BooleanField(default=False)),
                ('health_description', models.TextField(blank=True)),
                ('education_level', models.CharField(choices=[('fundamental', 'Ensino Fundamental'), ('medio', 'Ensino Médio'), ('faculdade', 'Faculdade')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsible', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='director_profile', to='core.responsible')),
            ],
        ),
    ]
