# Generated by Django 6.0 on 2026-02-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_monthlyfee_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsible',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/%Y/%m'),
        ),
    ]
