# Generated by Django 6.0 on 2026-02-01 18:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_responsible_signature_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_health_plan', models.BooleanField(default=False)),
                ('health_plan_name', models.CharField(blank=True, max_length=140)),
                ('health_plan_card', models.CharField(blank=True, max_length=140)),
                ('sus_card', models.CharField(blank=True, max_length=140)),
                ('catapora', models.BooleanField(default=False)),
                ('meningite', models.BooleanField(default=False)),
                ('hepatite', models.BooleanField(default=False)),
                ('dengue', models.BooleanField(default=False)),
                ('pneumonia', models.BooleanField(default=False)),
                ('malaria', models.BooleanField(default=False)),
                ('febre_amarela', models.BooleanField(default=False)),
                ('h1n1', models.BooleanField(default=False)),
                ('colera', models.BooleanField(default=False)),
                ('rubeola', models.BooleanField(default=False)),
                ('sarampo', models.BooleanField(default=False)),
                ('tetano', models.BooleanField(default=False)),
                ('variola', models.BooleanField(default=False)),
                ('coqueluche', models.BooleanField(default=False)),
                ('difteria', models.BooleanField(default=False)),
                ('caxumba', models.BooleanField(default=False)),
                ('rinite', models.BooleanField(default=False)),
                ('bronquite', models.BooleanField(default=False)),
                ('allergy_cutanea', models.BooleanField(default=False)),
                ('allergy_cutanea_detail', models.CharField(blank=True, max_length=255)),
                ('allergy_alimentar', models.BooleanField(default=False)),
                ('allergy_alimentar_detail', models.CharField(blank=True, max_length=255)),
                ('allergy_medicamento', models.BooleanField(default=False)),
                ('allergy_medicamento_detail', models.CharField(blank=True, max_length=255)),
                ('disability_type', models.CharField(choices=[('none', 'Sem deficiência física'), ('cadeirante', 'Cadeirante'), ('visual', 'Visual'), ('auditivo', 'Auditivo'), ('fala', 'Fala / dificuldade'), ('outra', 'Outra deficiência')], default='none', max_length=20)),
                ('heart_problem', models.BooleanField(default=False)),
                ('heart_medication', models.CharField(blank=True, max_length=255)),
                ('diabetic', models.BooleanField(default=False)),
                ('diabetic_medication', models.CharField(blank=True, max_length=255)),
                ('genital_problem', models.BooleanField(default=False)),
                ('genital_medication', models.CharField(blank=True, max_length=255)),
                ('psychological_problem', models.BooleanField(default=False)),
                ('psychological_medication', models.CharField(blank=True, max_length=255)),
                ('other_health_problem', models.BooleanField(default=False)),
                ('other_health_problem_detail', models.TextField(blank=True)),
                ('other_medication', models.BooleanField(default=False)),
                ('other_medication_detail', models.TextField(blank=True)),
                ('recent_health_issue', models.BooleanField(default=False)),
                ('recent_health_issue_detail', models.TextField(blank=True)),
                ('recent_medication', models.BooleanField(default=False)),
                ('recent_medication_detail', models.TextField(blank=True)),
                ('recent_injury', models.BooleanField(default=False)),
                ('recent_injury_detail', models.TextField(blank=True)),
                ('surgery', models.BooleanField(default=False)),
                ('surgery_detail', models.TextField(blank=True)),
                ('recent_change', models.BooleanField(default=False)),
                ('recent_change_detail', models.TextField(blank=True)),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('declaration_city', models.CharField(default='São Carlos', max_length=140)),
                ('declaration_date', models.DateField(default=datetime.date.today)),
                ('signature_data', models.TextField(blank=True)),
                ('adventurer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='core.adventurer')),
            ],
            options={
                'verbose_name': 'Ficha médica',
                'verbose_name_plural': 'Fichas médicas',
            },
        ),
    ]
