# Generated by Django 6.0 on 2026-01-28 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_directorapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorapplication',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='director_photos/%Y/%m'),
        ),
    ]
