# Generated by Django 6.0 on 2026-01-28 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_directorapplication_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directorapplication',
            name='term_rg_issuer',
        ),
    ]
