# Generated by Django 6.0 on 2026-01-28 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_directorapplication_term_rg_issuer'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorapplication',
            name='term_neighborhood',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='directorapplication',
            name='term_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='directorapplication',
            name='term_postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='directorapplication',
            name='term_state',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='directorapplication',
            name='volunteer_acceptance',
            field=models.BooleanField(default=False),
        ),
    ]
