# Generated by Django 6.0 on 2026-01-29 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_directorapplication_term_neighborhood_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventurer',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='blood_type',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='bolsa_familia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='certidao',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='classes_investidas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='cpf_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='family_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='grade',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='medical_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='parent_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='rg',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='rg_issuer',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='school',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='shirt_size',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='state',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='term_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
