# Generated by Django 6.0 on 2026-01-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_adventurer_address_adventurer_blood_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorapplication',
            name='term_data_truth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='directorapplication',
            name='term_signature',
            field=models.TextField(blank=True),
        ),
    ]
