# Generated by Django 6.0 on 2026-01-29 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_directorapplication_term_data_truth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorapplication',
            name='initial_data_truth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='directorapplication',
            name='initial_signature',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='directorapplication',
            name='volunteer_data_truth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='directorapplication',
            name='volunteer_signature',
            field=models.TextField(blank=True),
        ),
    ]
