# Generated by Django 6.0 on 2026-01-31 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_directorapplication_initial_data_truth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventurer',
            name='religion',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='responsible',
            name='relationship_degree',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
